"""

Revision ID: e620413f35c6
Revises: 
Create Date: 2022-06-28 19:43:50.873810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e620413f35c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('sum_bet', sa.Float(), nullable=False),
    sa.Column('deadline', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('NEW', 'FINISHED_WIN', 'FINISHED_LOSE', name='eventstate'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_id'), 'bet', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bet_id'), table_name='bet')
    op.drop_table('bet')
    # ### end Alembic commands ###
